version: "3.9"
services:
  api:
    build: .
    command: uvicorn concordia.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://concordia:concordia@db:5432/concordia
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: concordia
      POSTGRES_PASSWORD: concordia
      POSTGRES_DB: concordia
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
